### ISSUE TITLE
fallback of Object.assign

### ISSUE THREAD

**Issue by mattn** [huoy/moon#2]
how about this?
```javascript
var toml = require('toml');
var fs = require('fs');
var path = require('path');
var objectassign = require('object-assign')

var config = function() {
	var cfg = toml.parse(String(fs.readFileSync("config.toml")));
	return objectassign(cfg.common, cfg.client);
}();

module.exports = {
	entry: path.join(__dirname, config.dir, config.entry),
	output: {
		path: path.join(__dirname, config.static), 
		filename: config.js
	}
};
```

**Comment by huoy** [comment]
Hm, out of curiosity did you run into issues with Object.assign with an older version of node? Anyway you're right that it should probably be shimmed. Though I think I'll just rewrite it without the need for a dependency.

**Comment by mattn** [comment]
Object.assign is provided for ES6. I'm on windows10 with msys2. The version of nodejs is v0.10.40. It doesn't support ES6 (except using babel).

**Comment by huoy** [comment]
Ah, I see. Newer versions of node support a lot of the ES6 spec natively. But it's definitely an assumption that doesn't need to be made. Thanks.
